version: "2"

services:
  server:
    image: consul:1.0.7
    entrypoint: "server_setup.sh"
    command: "agent"
    environment:
      CONSUL_BIND_INTERFACE: eth0
    volumes:
      # those are our setup scripts
      - ./bin/server_setup.sh:/usr/local/bin/server_setup.sh
      - ./bin/server_acl_anon.sh:/usr/local/bin/server_acl_anon.sh
      - ./bin/server_acl_acl_token.sh:/usr/local/bin/server_acl_acl_token.sh
      - ./bin/server_acl_agent_token.sh:/usr/local/bin/server_acl_agent_token.sh
      # basic server configuration
      - ./consul-config/server_config.json:/consul/config/server_config.json
      - ./consul-config/server_acl.json:/consul/config/server_acl.json
      - consul-server-data:/consul/data:rw
      - consul-server-config:/consul/config:rw
      - consul-general-client-configs:/consul/clients-general
    ports:
      - "8500:8500"
    networks:
      default:
        ipv4_address: ${NETWORK_PREFIX}.254

  client1:
    image: consul:1.0.7
    entrypoint: client_setup.sh
    command: agent
    depends_on:
      - server
    volumes:
      - ./bin/client_setup.sh:/usr/local/bin/client_setup.sh
      - ./consul-config/agent_config-client1.json:/consul/config/agent_config.json
      - consul-general-client-configs:/consul/clients-general
    networks:
      - default

  client2:
    image: consul:1.0.7
    entrypoint: client_setup.sh
    command: agent
    depends_on:
      - server
    volumes:
      - ./bin/client_setup.sh:/usr/local/bin/client_setup.sh
      - ./consul-config/agent_config-client2.json:/consul/config/agent_config.json
      - consul-general-client-configs:/consul/clients-general
    networks:
      - default

volumes:
  logs:
    driver: local
  consul-server-data:
    driver: local
  consul-client1-data:
    driver: local
  consul-client2-data:
    driver: local
  consul-server-config:
    driver: local
  consul-general-client-configs:
    driver: local
  db:
    driver: local

networks:
  default:
    ipam:
      config:
        - subnet: ${NETWORK_PREFIX}.0/24
