version: "2"

services:
  server:
    image: consul:${CONSUL_VERSION}
    entrypoint: "server_boot.sh"
    command: "agent"
    hostname : consulserver1
    environment:
      SERVER_CONFIG_STORE: /consul/config
      CLIENTS_SHARED_CONFIG_STORE: /consul/clients-general
      ENABLE_APK: 1
      ENABLE_GOSSIP: 1
      ENABLE_ACL: 1
      ENABLE_TLS: 1
      CONSUL_HTTP_TOKEN_FILE: "/consul/config/.consul_cli_token"
      CONSUL_ALLOW_RESET_ACL: 1
    volumes:
      # those are our setup scripts
      - ./bin/server_boot.sh:/usr/local/bin/server_boot.sh
      - ./bin/server_setup_firstboot.sh:/usr/local/bin/server_setup_firstboot.sh
      - ./bin/server_setup_acl.sh:/usr/local/bin/server_setup_acl.sh
      - ./bin/server_setup_gossip.sh:/usr/local/bin/server_setup_gossip.sh
      - ./bin/server_setup_tls.sh:/usr/local/bin/server_setup_tls.sh
      - ./bin/server_setup_converge.sh:/usr/local/bin/server_setup_converge.sh
      - ./bin/server_acl_bootstrap.sh:/usr/local/bin/server_acl_bootstrap.sh
      - ./bin/server_acl_client_general_token.sh:/usr/local/bin/server_acl_client_general_token.sh
      # basic server configuration
      - ./consul-config/server_config.hcl:/consul/config/server_config.hcl
      - consul-server-data:/consul/data:rw
      - consul-server-config:/consul/config:rw
      - consul-general-client-configs:/consul/clients-general
    ports:
      - "8500:8500" #http, but will not be accessible ( should not be, we locked it down )
      - "8501:8501" #https
    networks:
      default:
        ipv4_address: ${NETWORK_PREFIX}.254

  client1:
    image: consul:${CONSUL_VERSION}
    entrypoint: client_boot.sh
    command: agent
    environment:
      CLIENTS_SHARED_CONFIG_STORE: /consul/clients-general
    depends_on:
      - server
    volumes:
      - ./bin/client_boot.sh:/usr/local/bin/client_boot.sh
      - ./consul-config/client1_config.hcl:/consul/config/agent_config.hcl
      - consul-general-client-configs:/consul/clients-general
    networks:
      - default

  client2:
    image: consul:${CONSUL_VERSION}
    entrypoint: client_boot.sh
    command: agent
    environment:
      CLIENTS_SHARED_CONFIG_STORE: /consul/clients-general
    depends_on:
      - server
    volumes:
      - ./bin/client_boot.sh:/usr/local/bin/client_boot.sh
      - ./consul-config/client2_config.hcl:/consul/config/agent_config.hcl
      - consul-general-client-configs:/consul/clients-general
    networks:
      - default

volumes:
  logs:
    driver: local
  consul-server-data:
    driver: local
  consul-client1-data:
    driver: local
  consul-client2-data:
    driver: local
  consul-server-config:
    driver: local
  consul-general-client-configs:
    driver: local
  db:
    driver: local

networks:
  default:
    ipam:
      config:
        - subnet: ${NETWORK_PREFIX}.0/24
