version: "2"

services:
  server:
    image: 0.7.4
    command: agent
    environment:
      CONSUL_BIND_INTERFACE: eth0
    volumes:
      - ./consul-config/server_config.json:/consul/config/server_config.json
      - consul-server-data:/consul/data:rw
    ports:
      - "8500:8500"
    networks:
      default:
        ipv4_address: ${NETWORK_PREFIX}.254

  client:
    image: 0.7.4
    command: agent
    depends_on:
      - server
    volumes:
      - ./consul-config/agent_config.json:/consul/config/agent_config.json
      - consul-client-data:/consul/data:rw
    networks:
      - default

volumes:
  logs:
    driver: local
  consul-server-data:
    driver: local
  consul-client-data:
    driver: local
  consul-config:
    driver: local
  db:
    driver: local

networks:
  default:
    ipam:
      config:
        - subnet: ${NETWORK_PREFIX}.0/24
