name: test-acls

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: version
        run: docker-compose --version
      - name: start stack
        run: |
          cd acls 
          docker-compose --version
      - name: run tests
        run: |
          cd acls
          ./test.sh
