name: test-acls

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - shell: bash
        run: |
          cd acls
          docker-compose up -d
          # waiting for the stack to start up
          
          sleep 20
          echo "running tests"
          ./test.sh
